### ISSUE TITLE
Hostname based configuration of OIDC and OAuthBearer

### ISSUE THREAD

**Issue by csunali** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#107]
Hey everyone,

I am asking the same question here since some of you might have already needed to solve the same use case and the case is explicitly about OIDC and OAuthBearer (though it is not limited to these two).

I have asked a question on the ASP.NE repo, could you please have a look and comment if you have any ideas?

https://github.com/aspnet/Home/issues/743

**Comment by PinpointTownes** [comment]
Hey,

Multi-tenancy has always been a thorny topic, even back to the Katana era :smile:
Sadly, it's still not implemented in ASP.NET 5: https://github.com/aspnet/Security/issues/35

In theory, you should be able to create a custom `IOptions<OpenIdConnectServerOptions>` and return a different instance for each request, depending on the hostname, the path, a query string parameter, a header... :

```csharp
public void ConfigureServices(IServiceCollection services) {
    services.AddScoped<IOptions<OpenIdConnectServerOptions>, MyOptions>();
}

public class MyOptions : IOptions<OpenIdConnectServerOptions> {
    private readonly IHttpContextAccessor context;

    public MyOptions(IHttpContextAccessor context) {
        this.context = context;
    }

    public OpenIdConnectServerOptions Options => GetNamedOptions(name: null);

    public OpenIdConnectServerOptions GetNamedOptions(string name) {
        // Extract the tenant identifier and use it to return different options.
        // You could extract if from a header, from the query string,
        // from the path and of course, from the hostname.
        var tenant = context.HttpContext.Request.Headers["Tenant-ID"];

        return new OpenIdConnectServerOptions {
            Issuer = new Uri("http://www.google.com/")
        };
    }
}
```

Sadly, this won't work, as `AuthenticationMiddleware` calls `IOptions<>.Options` directly in its constructor (where you can't access the current request, since there's simply none :smile:) and stores it as a singleton: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/AuthenticationMiddleware.cs#L26-L34

To support multi-tenancy, `AuthenticationMiddleware`'s inheritors would also have to update their constructor, to avoid accessing the options instance too early. I guess we'd need a `ValidateOptions` directly in `AuthenticationMiddleware` to delay options validation.

You should probably try to revive the existing ticket on `aspnet/Security` and suggest a few changes to make this scenario work: https://github.com/aspnet/Security/issues/35

**Comment by PinpointTownes** [comment]
Closing as it's not something we can include in ASOS without built-in support in the base authentication middleware.

**Comment by csunali** [comment]
I was just able to read your previous response. Thank you for your feedback. Let's see what happens at aspnet/Security#35
