### ISSUE TITLE
Authorization endpoint should enforce client_id validation.

### ISSUE THREAD

**Issue by ilmax** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#110]
Actually is possible to proceed with a malformed authentication request, the specs says that client_id is required, but validating the notification in ```ValidateClientRedirectUri``` make the request proceed anyway

**Comment by PinpointTownes** [comment]
Thanks for reporting this issue! :smile: 

Indeed, back to the `OAuthAuthorizationServerMiddleware` era, you were supposed to validate the `client_id` in the `ValidateClientRedirectUri` notification and reject the request if the `client_id` parameter was missing or invalid.

That said, adding an early check to ensure that the `client_id` is not missing definitely makes sense and shouldn't cost anything.

**Comment by PinpointTownes** [comment]
Fixed in both versions (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/8729cd10670e230495b5a6fa63e51640ee8c937e; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/433681de12a4fb4f9ba73bbc3267b4de82d42d1b) :carousel_horse:
