### ISSUE TITLE
Implicit Flow lacks nonce check

### ISSUE THREAD

**Issue by ilmax** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#111]
Implicit flow require the nonce parameter is present in the authentication request, actually because we support OAuth2 flows, this check is not present.

In case the current authentication request is an openid connect request, we should enforce nonce validation.

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug :smile: 

Fixed in both versions (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/b792dc7b8a87b3824e6ce014471c18ad59010a60; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/c2e5745857a6f6348f5903e4a16c9bea8cc31705).
