### ISSUE TITLE
Identity Token creation & Implicit Flow

### ISSUE THREAD

**Issue by ilmax** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#112]
Identity Token generation requires that the identity representing the signed in user has a claim of type ```ClaimTypes.NameIdentifier```, and it will throw otherwise.

Actually the method swallows the exception and keep going processing the request, resulting in an invalid response being sent to the client, because no id_token is present and, accordingly to the specs, this is a mandatory parameter in a successful authentication response.

This can partially apply for hybrid flow either.

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug, I'll fix it today (unless you REALLY want to fix it yourself :smile:)

**Comment by PinpointTownes** [comment]
Fixed in both versions (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/e120e824328d0ef837b6f942f6d8100e5022b2f3; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/8c07efe62ff93fd03845a4c6c317a934f6f07005) :balloon: 

A `server_error` response will now be returned if either the `code`, the `id_token` or the `access_token` is missing from the authorization response (of course, no error is returned when it was not listed in `response_type`).
On the token endpoint, it's a bit different: no error is returned if the refresh token is missing while an error is always returned if `access_token`. For `id_token`, an error is only returned if an `openid` scope was included in either the authorization request or in the token request.

Thanks! :smile:
