### ISSUE TITLE
inconsistent naming

### ISSUE THREAD

**Issue by stephenstroud** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#118]
Which namespace should I use Authentication or Security?? I read that the security name had been replaced with Authentication but this project is still active and using Security.  I'm trying to implement bearer token server for a mobile app using VNext but finding different info that isn't consistent.
 
which is it?
Microsoft.AspNet.Authentication.OpenIdConnect
AspNet.Security.OpenIdConnect.Server

Within the server sample the reference to OpenidConnect doesn't have a version?

 "AspNet.Security.OpenIdConnect.Server": ""

I'm following this post but not having much luck as things seem inconsistent

http://stackoverflow.com/questions/30768015/configure-the-authorization-server-endpoint/30788109#30788109 

Any pointers please, which should I use? 

I'm not finding AspNet.Security.OpenIdConnect.Server or nuget ot MyGet.

Thanks

**Comment by PinpointTownes** [comment]
Hey,

> Which namespace should I use Authentication or Security?? I read that the security name had been replaced with Authentication but this project is still active and using Security. I'm trying to implement bearer token server for a mobile app using VNext but finding different info that isn't consistent.

We're still using `Security` (instead of `Authentication`) for at least two reasons:
* it's the standard naming scheme for OWIN/Katana security packages (`Microsoft.Owin.Security.*`). Since we have packages for both OWIN/Katana and ASP.NET 5, it's better to keep everything consistent.
* OpenID Connect is both an authentication and an authorization protocol: replacing `Security` by `Authentication` would be too restrictive. `Security` is neutral enough to cover both concepts.

> which is it?
Microsoft.AspNet.Authentication.OpenIdConnect
AspNet.Security.OpenIdConnect.Server

`Microsoft.AspNet.Authentication.OpenIdConnect` is the name of the **OpenID Connect client** middleware developed by the ASP.NET team. It's part of the `aspnet/Security` repository: https://github.com/aspnet/Security

`AspNet.Security.OpenIdConnect.Server` corresponds to the **OpenID Connect server** hosted on this GitHub repository, but I guess you've already figured it out :smile: 

> Within the server sample the reference to OpenidConnect doesn't have a version?
"AspNet.Security.OpenIdConnect.Server": ""

When referencing a vNext project that is part of the same solution, you don't need to specify the package/project version. That said, the ASP.NET no longer uses this pattern, even in their samples. I'll update that to keep everything consistent.

> Any pointers please, which should I use?

You should always use `"AspNet.Security.OpenIdConnect.Server": "1.0.0-*"` to reference the latest version.

> I'm not finding AspNet.Security.OpenIdConnect.Server or nuget ot MyGet.

It's on our MyGet nightly repository (mentioned in the README.md file):
https://www.myget.org/F/aspnet-contrib/

Here's the latest package available ATM: https://www.myget.org/F/aspnet-contrib/api/v2/package/AspNet.Security.OpenIdConnect.Server/1.0.0-beta2-0290

**Comment by stephenstroud** [comment]
@PinpointTownes Thank you!
