### ISSUE TITLE
Enhancement: Support for encrypted JWTs (JWE standard)

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#120]
I've been learning more about this middleware over the past few days, and I noticed that it does not seem to support any kind of encrypted JWTs at present (I'm working in .net 4.5.1/4.5.2), as it uses Microsoft's JwtSecurityTokenHandler class, and that does not support encryption.

I'd like to suggest functionality be added for this capability in order to support encrypting sensitive (claim) data.

**Comment by PinpointTownes** [comment]
I agree that supporting encrypted JWTs access/identity tokens would be a nice addition. Sadly - as you've already figured out - it's not yet supported by `IdentityModel`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/46

Luckily, there's a way to work around this limitation: with `AspNet.Security.OpenIdConnect.Server`, you can fully control the way tokens are generated using the `CreateIdentityToken` and `CreateAccessToken` notifications, which means that you're totally free to use another library that supports JWE (like `jose-jwt`: https://github.com/dvsekhvalnov/jose-jwt).

Simply set `notification.AccessToken = [your token]` and call `notification.HandleResponse()` from `IOpenIdConnectServerProvider.CreateAccessToken` and `OpenIdConnectServerMiddleware` will use your own token (even if it's totally invalid :smile:) instead of generating a new one using `JwtSecurityTokenHandler`.

For access tokens, you could also consider using opaque tokens: unlike JWT tokens, they are serialized using the data protection block offered by ASP.NET and CANNOT be read by client applications or user agents. Simply call `app.UseOpenIdConnectServer(options => options.UseOpaqueTokens())` and it will stop issuing JWT access tokens. Note that depending on the nature of the resource server you're using, it might be a bit complicated to update it to support these tokens. In this case, feel free to use the token validation endpoint for that.

Finally, you can also mix both options with "reference tokens": use the `CreateAccessToken` notification, generate a unique identifier, store the corresponding identity in the database, and use the identifier as the access token. The token validation endpoint may also help you for this approach.

Good luck :+1:

**Comment by MonkeyJamboree** [comment]
One small note: Discovery via the configuration and cryptography endpoints also might (should?) be a consideration if someone uses another library to support encrypted tokens. I would think that when/if it becomes supported in IdentityModel, the middleware should support discovery of that information, but that's neither here nor there.

Thanks for the suggestions for workarounds.

**Comment by PinpointTownes** [comment]
In the next beta version, we'll start using opaque tokens again: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/185 :tada:
