### ISSUE TITLE
Version package name by .net conversion

### ISSUE THREAD

**Issue by singlewind** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#121]
Today, I tried to debug an issue which doesn't make sense to me. Finally, I found that because I have referenced two packages which reference the same package with different version. Since .NET core use DI a lot. Which means it won't give compile error but throw runtime error when the class has break changes in two different version. For example, I have AspNet.Security.OpenIdConnect.Server package reference all the beta7 packages. But on my main web application I've referenced all the beta6 packages. I know at the end of day, I have to move to beta7 as well. However, it should be act like process. For example upgrade all the projects in the solution at the same time when beta7 get stable and other projects has caught up the progress to update theirs as well.

The solution of ASP.NET team made is that they set their beta version to match the .NET Core version. For example, all the beta6 ASP.NET packages are supposed to work with .NET Core beta6 version and compatible with all other beta6 microsoft packages. All we need to do is modify the project.json file to make sure version number matches the other packages. Then when user reference that package will more confident to know whether fit in their solution at the moment. Or they can use previous package which fits temporarily.  

At the moment, the stable version of .net core is 1.0.0-beta6 and possibly 1.0.0-beta7 tomorrow. So, we can update version to 1.0.0-beta7 instead of 1.0.0-beta2. Also update all the wildcard dependencies to beta7 specified. When .NET Core beta8 released, we can update all of them.

I'm open to discuss this as well. I'm seeking a pattern to work better with open source projects which their the API of dependencies changes every build.

**Comment by PinpointTownes** [comment]
Interesting suggestion. A few remarks though:

> For example, all the beta6 ASP.NET packages are supposed to work with .NET Core beta6 version and compatible with all other beta6 microsoft packages.

I'm not sure where you've found a beta6 version for .NET Core packages since the CLR team doesn't use the beta* pattern:

![capture-829382938923](https://cloud.githubusercontent.com/assets/6998306/9587282/fe30cd5a-5021-11e5-93f3-e6c9f8129193.PNG)

https://www.nuget.org/packages/Microsoft.AspNet.DataProtection/

> So, we can update version to 1.0.0-beta7 instead of 1.0.0-beta2.

I agree this would be really convenient. Sadly, this would also mean we would have to strictly follow the timeline used by the ASP.NET team, which doesn't seem really flexible. I'm not opposed to your suggestion, but it definitely needs a long-term approach.

FYI, beta7 packages should be released today by the ASP.NET team. For the first time, I'll also release a beta2 version of the various `aspnet-contrib` projects on NuGet.org: they will target ASP.NET 5 beta7 packages and should offer a much more stable experience than nightly builds.

**Comment by singlewind** [comment]
@PinpointTownes thanks Kevin, you get what I mean. Sorry for the confusion. Your are right the beta name convention is mainly for core clr. Some of teams already release their beta8 packages a week ago which means if we doesn't specify version, it may use the beta8 package when we restore. Thanks for create a stable repository on NuGet.org.

**Comment by singlewind** [comment]
Sorry @PinpointTownes  I'm not trying to chase you on this. Any updates on this?

**Comment by PinpointTownes** [comment]
ASP.NET 5 beta7 packages were released today, but a critical package was missing from NuGet.org. This is now fixed and all our beta packages are ready to be published. I'll finalize everything tomorrow :+1:

**Comment by singlewind** [comment]
Thanks :+1:

**Comment by PinpointTownes** [comment]
Wooooot, we're now officially on NuGet.org: https://www.nuget.org/profiles/aspnet-contrib :tada: 

![Party haaaaard!](http://media2.giphy.com/media/hsBZfDG7wiWHu/giphy.gif)

![Party haaaaard!](http://vignette1.wikia.nocookie.net/epicrapbattlesofhistory/images/1/13/Party-hard.gif/revision/latest?cb=20130928233610)
