### ISSUE TITLE
MVC.Server HttpGet "SignIn" method on Authentication Controller, line 17

### ISSUE THREAD

**Issue by Sharpiro** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#127]
It looks like an Error is occuring near: MVC.Server,  HttpGet "SignIn" method on Authentication Controller, line 17.

```
Method not found: 'Microsoft.CodeAnalysis.Emit.EmitResult Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken
```

**Comment by Sharpiro** [comment]
On an unrelated note, do you have any example of using OpenIdConnect.Server with Bearer/Grant_type=password/GrantResourceOwnerCredentials style?  I'm trying to implement something where I can get an access token from a username/password using javascript and http methods.

**Comment by PinpointTownes** [comment]
Thanks for reporting this issue and sorry the late reply.

I'm tempted to say it's a Roslyn bug that appears when using `dynamic`. I'll ping @davidfowl tomorrow and see if it's just a transient bug. In the meantime, you can use `ViewData` as a good old dictionary :smile: 

For a sample implementing the ROPC grant type, you should have a look at @louislewis2's sample: https://github.com/louislewis2/Aurelia-Demo/. It's still a WIP but it's a great starting point demonstrating how you can use ROPC with a JS client app.

**Comment by pabitra** [comment]
Hi I was trying to run the code but I am getting some runtime exception i.e. {"Unable to cast object of type 'Microsoft.AspNet.Server.WebListener.FeatureContext' to type 'Microsoft.AspNet.Http.Features.IHttpWebSocketFeature'."}

**Comment by PinpointTownes** [comment]
@pabitra hey. I started seeing this error recently with WebListener, not sure what's causing it (/cc @Tratcher)

The best way to work around this bug is to use Kestrel, which is the universal and recommended web server in vNext anyway. The MVC sample has been moved to https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples and updated to target RC1 and use the new HttpPlatformHandler hosting model.

**Comment by Tratcher** [comment]
Stack trace?
https://github.com/aspnet/Announcements/issues/126

**Comment by PinpointTownes** [comment]
We don't use WebSockets, but it might be caused by the OWIN bridge:

> Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request starting HTTP/1.1 GET http://localhost:54540/favicon.ico  
Microsoft.AspNet.Server.WebListener.MessagePump: Error: ProcessRequestAsync
System.InvalidCastException: Impossible d'effectuer un cast d'un objet de type 'Microsoft.AspNet.Server.WebListener.FeatureContext' en type 'Microsoft.AspNet.Http.Features.IHttpWebSocketFeature'.
   à Microsoft.AspNet.Http.Features.FeatureCollectionExtensions.Get[TFeature](IFeatureCollection features)
   à Microsoft.AspNet.Http.Features.FeatureHelpers.GetAndCache[T](IFeatureCache cache, IFeatureCollection features, T& cachedObject)
   à Microsoft.AspNet.Http.Internal.DefaultWebSocketManager.get_WebSocketFeature()
   à Microsoft.AspNet.Http.Internal.DefaultWebSocketManager.get_IsWebSocketRequest()
   à Microsoft.AspNet.Owin.OwinEnvironment..ctor(HttpContext context)
   à Microsoft.AspNet.Builder.OwinExtensions.<>c__DisplayClass0_0.<UseOwin>b__3(HttpContext httpContext)
   à Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Microsoft.AspNet.Hosting.Internal.HostingApplication.<ProcessRequestAsync>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   à Microsoft.AspNet.Server.WebListener.MessagePump.<ProcessRequestAsync>d__26.MoveNext()
Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request finished in 15ms 500

**Comment by Tratcher** [comment]
Woops, missed a spot. Thanks for the heads up.
