### ISSUE TITLE
Signature validation fails when mixing IdentityModel 4.0 and IdentityModel 5.0

### ISSUE THREAD

**Issue by marc-mueller** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#132]
When we setup a sample application with Asp.NET MVC 5 to authenticate against the OIDC Server implementation, the signature validation will fail.

We receive the following exception:
```
IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 1,
    Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
    )
```
The metadata just looks right but it is not possible to validate the signature. I created a repro solution under: https://github.com/marc-mueller/AspNet.Security.OpenIdConnect.Server-MVC5Compatibility. Just start it up a click on one of the links "about" or "contact" and you will see the exception.

What is causing this error / key mismatch?

**Comment by PinpointTownes** [comment]
After an intensive debugging session, I finally found the root cause of this issue.

There's actually a subtle different between the tokens generated by IdentityModel 4.0 (used in Katana) and IdentityModel 5.0 (used in ASP.NET 5).

![image](https://cloud.githubusercontent.com/assets/6998306/9913988/01ba963c-5cb0-11e5-86c0-76694705d1ce.png)

![image](https://cloud.githubusercontent.com/assets/6998306/9914090/7b550496-5cb0-11e5-9301-d2c51d4bbde2.png)

IdentityModel 5.0 is a bit smarter than its old parent as it's able to retrieve the certificate hash from `X509SecurityKey` (while IM 4.0 was only able to extract it if you used a `X509SigningCredentials` instance), and that's why we automatically get a "kid" (key identifier) in the tokens issued using IM 5.0.

Sadly, this subtle difference has a side-effect: when validating the token, IM 4.0 will try to resolve the issuer key using the "kid" and the corresponding key in the JWKS exposed by the identity server.

We don't expose "kid" on this endpoint so IM 4.0 shouldn't try to resolve it using "kid"... but there's an obscure bug in IM 4.0 that prevents the "fallback mode" from working correctly, even if you explicitly specify a "kid" in the JWKS: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/181

Since I have the weird feeling this bug won't be fixed in the near future, I had to find a workaround: it seems that explicitly exposing the `x5t` (certificate hash) in the key itself makes IM 4.0 use certificate hash comparison instead of key identifier comparison, allowing it to work correctly.

I'll upload the workaround soon.

**Comment by marc-mueller** [comment]
Thanks a lot for your effort and quick response. We are looking forward to the mentioned workaround.

**Comment by PinpointTownes** [comment]
It should be fixed via https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/0815f2ba874ff5248d9b752dc788d9f6b9f9458e (ASP.NET 5). Please ping me to confirm that's the case when you have time :+1: 

Similar changes have been added to the OWIN/Katana version: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/1245b2184d9b6f8db67a1e30f1cf3519a04aa749.

**Comment by PinpointTownes** [comment]
The updated package is on MyGet: https://www.myget.org/F/aspnet-contrib/api/v2/package/AspNet.Security.OpenIdConnect.Server/1.0.0-beta3-0344

**Comment by PinpointTownes** [comment]
Closing. Feel free to re-open it if the bug reappears.
