### ISSUE TITLE
unique_id in the examples

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#134]
I tried to make some sense of it, but couldn't - what exactly is the `unique_id` used for in `/connect/authorize` ([here](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L57))? It doesn't seem to be used anywhere except for passing it to the view, which in turn passes it to `/connect/authorized/accept` or `/connect/authorize/deny` where it is then ignored.

**Comment by PinpointTownes** [comment]
When an authorization requests arrives at the corresponding endpoint, it is automatically serialized and stored in a distributed cache to make it easier to flow.

Why? Mainly because we support POST authorization requests: these requests can be really large and potentially exceed the limits of URLs. Since the MVC sample redirects the user to Google or Twitter using a GET request, we need to store the request somewhere to avoid URL length issues.

Once stored in the cache, the OIDC parameters are replaced by a single `unique_id`. Calling `context.GetOpenIdConnectRequest()` on the authorization endpoint (the `Authorize` action in the MVC sample) allows you to retrieve the authorization request from the cache, just as if it was extracted from the query string.

**Comment by sunsided** [comment]
That makes things clearer. Thanks! :+1:

**Comment by damccull** [comment]
Totally useful info. Add to docs!
