### ISSUE TITLE
Configuration vs Options

### ISSUE THREAD

**Issue by Igorbek** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#145]
Hi,

I haven't updated the library since beta2, and today I did it.
I found that moving from options to configuration has introduced some inconveniences. By configuration approach I mean that configuring the service is only possible by passing function that accepts configuration object.

There are a few reasons why I think so:
- `OpenIdConnectServerConfiguration` cannot be created (the constructor is internal)
- `OpenIdConnectServerConfiguration` has no setter for `Options` and `Provider`
- there is no way to use existing `OpenIdConnectServerOptions` instance that might be created out of startup unless all the properties will be explicitly copied; it makes much harder to separate configuring and including the middleware into pipeline.
- moreover, extension functions now only applicable to a configuration object and cannot be applied to an options, so it is just impossible to configure detached from startup process - without `IAppBuilder` (or only by passing a function).
- usually, OWIN authentication middlewares use 'options' as a first-class citizens and allow to simply pass it during app building.

What was the reason behind this decision? I was able to find only commit message:
> Introduce OpenIdConnectServerConfiguration to enable services-dependent extensions support

Is it final? Are you having any plans to rationalize it?

**Comment by PinpointTownes** [comment]
As you've already figured out, `OpenIdConnectServerConfiguration` was introduced because we needed the services container for specific extensions (like `UseKeys`, that requires a data protector). 

The `app.UseOpenIdConnectServer()` extension taking an `OpenIdConnectServerOptions` was removed to encourage you to use the delegate extension, that will automatically set some properties for you (like `AllowInsecureHttp` in development/testing environments).

Providing two extensions with a different behavior was confusing and that's why I removed the second one.

But actually, you still can directly flow a `OpenIdConnectServerOptions` instance by using `app.UseMiddleware<OpenIdConnectServerMiddleware>(options)`, which is basically what the extension did.

If I re-introduce it, it will probably be decorated with `[EditorBrowsable(EditorBrowsableState.Never)]` to avoid showing it in Intellisense and encourage people to use the other overload.

**Comment by Igorbek** [comment]
Would it be possible to introduce `Use...` overload that takes an options object in addition to function that you can initialize configuration with this?
The main concern is that options class isn't a first-class citizen anymore. That restricts flexibility.

**Comment by MonkeyJamboree** [comment]
Is there a reason the services container isn't just passed to the `OpenIdConnectServerOptions` and extensions used on it? Or the extensions used on `OpenIdConnectServerMiddleware` itself?

**Comment by PinpointTownes** [comment]
> Is there a reason the services container isn't just passed to the OpenIdConnectServerOptions and extensions used on it?

The reason is only about semantic: the services container is not an option :smile: 
That said, it would change anything since we'd still have to initialize this property at some point (just like we do for `OpenIdConnectServerConfiguration.Builder`)

**Comment by Igorbek** [comment]
That's ok to have configuration (or builder?) that depends on IAppBuilder. But, I believe, the options object have to be the primary transferable object. i would like to have the following options:
```cs
app.UseOpenIdConnectServer(options); // options can go alone
app.UseOpenIdConnectServer(
  options, // options might be passed with configurator
  config => { ... });
app.UseOpenIdConnectServer(
  config => {
    config.Options = options; // options might be set from the configurator
    ...
  });
```

So just a couple of additional overloads and public setter for `Options` property.
Do you think it will break some concepts?

**Comment by PinpointTownes** [comment]
I'm not opposed to making the `Options` property settable :+1:

**Comment by Igorbek** [comment]
Let me do this PR then! :)

**Comment by PinpointTownes** [comment]
Off-topic: IIRC, you had plans to add the missing session management features in ASOS and that's something I'd like to do in the near future. Have you finally implemented it?

**Comment by PinpointTownes** [comment]
Feel free to also rename `OpenIdConnectServerConfiguration` to `OpenIdConnectServerBuilder` :+1:

**Comment by Igorbek** [comment]
Yes, I've done this. I implemented it as an extension that uses provider and introduce some other endpoints. It also has client-side extension, as Microsoft's middleware doesn't support it.
I'll think how to make it pluggable and create PR.

**Comment by PinpointTownes** [comment]
That would be great, thanks! :clap:

**Comment by MonkeyJamboree** [comment]
Oh awesome, session management was another thing that I had planned to start work on in the future sometime. Glad to hear it's been done already!

**Comment by PinpointTownes** [comment]
@Igorbek FYI, I just pushed a commit making `OpenIdConnectServerBuilder`'s constructor public.

**Comment by Igorbek** [comment]
That's great! Thanks.
If I make some `Use*` extensions that doesn't require `IAppBuilder`, also available for Options (in addition to builder), would it be accepted?

**Comment by PinpointTownes** [comment]
I think it would be going too far. And most of the existing extensions will eventually the services container when we implement logging.

**Comment by Igorbek** [comment]
I'm specifically interested in `UseCertificate`/`UseKeys` as they seem to be just an options without behavior (service). I would better have extension over `IList<SigningCredentials>` and call them `AddCertificate` and `AddKeys`. Do you think it makes sence?

**Comment by PinpointTownes** [comment]
@Igorbek you'll be happy to hear that I've decided - per your initial suggestion - to revert all the changes discussed in this ticket: `OpenIdConnectServerBuilder` was removed and the `UseOpenIdConnectServer` extension directly taking an `OpenIdConnectServerOptions` was re-introduced.

All the `AddKeys`/`UseKeys` extensions have been removed. This means that you can no longer set the directory used to store the dynamically-generated keys. The main idea behind this change is to encourage people to use a X509 certificate when going live while offering a frictionless experience during the development stage (a warning message will be automatically logged if no explicit key/certificate is added by the developer).

The `UseKey`/`UseCertificate` extensions have been replaced by their `AddKey`/`AddCertificate` counterparts to avoid ambiguities between signing and encryption credentials, which means that you'll now have to use `options.SigningCredentials.AddCertificate(...)` instead of `options.UseCertificate(...)`.

Hope you'll like the changes.

**Comment by Igorbek** [comment]
Oh, that's great. Thank you for hearing me :) I'm closing the issue.
