### ISSUE TITLE
Re-evaluate default code/token lifetime

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#146]
Current default values:

```csharp
public TimeSpan AuthorizationCodeLifetime { get; set; } = TimeSpan.FromMinutes(5);

public TimeSpan AccessTokenLifetime { get; set; } = TimeSpan.FromHours(1);

public TimeSpan IdentityTokenLifetime { get; set; } = TimeSpan.FromMinutes(20);

public TimeSpan RefreshTokenLifetime { get; set; } = TimeSpan.FromHours(6);
```

**Comment by MonkeyJamboree** [comment]
According to http://openid.net/specs/openid-connect-core-1_0.html#TokenLifetime it seems that access token lifetime should be a very short interval. It mentions them being single-use, so that may be an option for further configuration down the road, however to me single-use access tokens seem a bit too unwieldy for real-world usage. I think a number of minutes (15? 30?) makes sense for this.

As for refresh token lifetimes, a period of "X days" makes more sense to me for defaults here, thinking from a user reauthorization standpoint - it's annoying for users to have to re-authorize applications every day (or every few days) they use them, for instance. 15 days allows for a two-week period before a user would have to re-authorize if authorization depends on the life of the refresh token. (Also, sliding expiration and generation of new refresh tokens each request seems like a nice couple of configuration features if not already implemented.)

5 Minutes makes sense to me for Authorization Codes since it accounts for lag and transmission delays, but is short enough that they don't last very long at all.

According to http://stackoverflow.com/questions/25686484/what-is-intent-of-id-token-expiry-time-in-openid-connect and based on the description of the "exp" claim in the spec, I get the impression that ID Token expiration really is just for client validation purposes - I.E. if the ID Token's "exp" claim has a value on or before the current time, the client shouldn't accept or use it. As such, I believe another short timeframe would be good for this. Matching the Access Token lifetime makes sense to me as clients may want to refresh their ID Token when requesting a new Access Token on behalf of a subject.

**Comment by stephenstroud** [comment]
Single-use access token life span of 1 hour would be a nice default.

Sliding expiration isn't a feature, I thought it would be a nice to have but leads to other issues as the tokens are self contained as the doc says "Access Tokens might not be revocable by the Authorization Server." As revoking the token isn't a default feature sliding may be a bad idea.   

15 days seems extreme for a token life span, but that would depend on what the application is used for.

**Comment by MonkeyJamboree** [comment]
The sliding expiration and 15 day comments were directed explicitly toward refresh tokens, which serve a different purpose. According to http://tools.ietf.org/html/rfc6749#section-6, "Because refresh tokens are typically long-lasting credentials used to request additional access tokens, the refresh token is bound to the client to which it was issued." Since "Refresh tokens are issued to the client by the authorization server and are used to obtain a new access token when the current access token becomes invalid or expires, or to obtain additional access tokens with identical or narrower scope" (http://tools.ietf.org/html/rfc6749#section-1.5), the intent seems to be more aimed at not having to re-authorize in various flows, and thus it makes sense to me to not require re-authorization within a long enough time span that user experience doesn't suffer. This could be done via one or both of sliding expiration or a long expiration time span. These are also only defaults and of course customizable by the consumer. (Also, it seems sliding expiration IS already supported for refresh tokens themselves.)

**Comment by PinpointTownes** [comment]
> I get the impression that ID Token expiration really is just for client validation purposes - I.E. if the ID Token's "exp" claim has a value on or before the current time, the client shouldn't accept or use it. As such, I believe another short timeframe would be good for this.

Yep, you're right. When an `id_token` is received by the authorization server (via `id_token_hint` for instance), its expiration date is always ignored, which means you can use even really old identity tokens to trigger a `prompt=none` re-authentication.

> Also, it seems sliding expiration IS already supported for refresh tokens themselves

Yup, it is even enabled by default to match OAuthAuthorizationServerMiddleware's default behavior:

```csharp
/// <summary>
/// Determines whether refresh tokens issued during a grant_type=refresh_token request should be generated
/// with a new expiration date or should re-use the same expiration date as the original refresh token.
/// Set this property to <c>true</c> to assign a new expiration date each time a refresh token is issued,
/// <c>false</c> to use the expiration date of the original refresh token. When set to <c>false</c>,
/// access and identity tokens' lifetime cannot exceed the expiration date of the refresh token.
/// </summary>
public bool UseSlidingExpiration { get; set; } = true;
```


Okay, so let's sum up:

* `AuthorizationCodeLifetime` and `IdentityTokenLifetime`'s default values seem appropriate.
* 1 hour for `AccessTokenLifetime` appears to be a good compromise (FYI, Azure Active Directory uses the same time span, and you can't change it).
* `RefreshTokenLifetime`'s default definitely need to be re-evaluated: 15 days, as suggested by @MonkeyJamboree seems a good value if we leave `UseSlidingExpiration` true by default.

**Comment by louislewis2** [comment]
I think that the default values suggested above make perfect sense. The change in the RefreshTokenLifetime to 15 days would be very welcomed by us as a new default. In my opinion if the Azure team is using 1 hour for the AccessTokenLifetime using that same value here makes great sense too.

**Comment by DovydasNavickas** [comment]
@MonkeyJamboree said everything, @PinpointTownes summarized it and I agree on all of that.
I think for good user experience refresh tokens need to be valid for 15 days (at least).
And Access tokens matching Azure AD token lifetime comes as a nice bonus.
Good job on this!

**Comment by Jak3b0** [comment]
@PinpointTownes The proposed default values makes a lot of sense to me. +1

**Comment by PinpointTownes** [comment]
Any objection to using 14 days instead of 15 for the refresh token lifetime? (which is the lifetime used by AAD for its refresh tokens)

**Comment by MonkeyJamboree** [comment]
No objection here. That's 2 weeks exactly.

**Comment by Jak3b0** [comment]
Same here... Make more sense.

On Sun, Nov 8, 2015, 2:44 PM Michael Ciarlillo <notifications@github.com>
wrote:

> No objection here. That's 2 weeks exactly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/146#issuecomment-154860755>
> .
>
-- 

Jacques

**Comment by PinpointTownes** [comment]
Done, thanks for your participation guys! :tada: 

ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/5c39b806f05d16ea0bb01fd1e2df4fe0f915de61
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/ba741d4cb3e25f1ba575b34a314d1d482497bee3
