### ISSUE TITLE
Support for the full Session Management (draft) spec

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#168]
Add support for the [Session Management spec](http://openid.net/specs/openid-connect-session-1_0.html).

**Comment by Igorbek** [comment]
I can describe what I've implemented, so we could think how to port to the library. I have no time right now, I'll do it during the day.

**Comment by MonkeyJamboree** [comment]
I'm definitely interested in seeing this spec implemented at some point (probably the next "big feature" I'll work on after Dynamic Registration unless someone else gets to it first). @Igorbek whenever you get some time, I'm interested in hearing what you did. :+1:

**Comment by PinpointTownes** [comment]
> @Igorbek whenever you get some time, I'm interested in hearing what you did. :+1:

Yeah, that would be great, @Igorbek! :clap:

**Comment by Igorbek** [comment]
Guys, I'm so sorry for such a delay.
Ok, I'll try to describe from high-level and go into details later.

### Overview
The idea behind session management is to issue some session state token to the client when it performs authentication in order to be asking, within browser context, about current session state during authentication session lifetime.
The implementation is separated for two parts - server and client, obviously. The most complicated part is client, though.
I assume, the reader is familiar with the spec.

### Server
The session state token must:
- be tied with client_id
- be tied with end-user's session
- have entropy
- be hashed (better) or encrypted
- be impossible to reverse engineer
- not disclose any user-related information
- not disclose the fact that user logged in or not

> *My implementation note*
> Because in my scenarios, I always have a cookie authentication as the primary authentication type on the server, and sinse it is already contains all the information I want to depend on, I decided to calculate session state based on authenticatioin cookie value. So my server extension, on authorize response adds additional value `session_state` (which is already defined in the message format).

However, there're a couple of flows that need to be considered:
- if end-user wasn't authenticated and non-interactive flow was requested, the server must reject _but_ might provide session state even though. That is important to detect non-authenticated users. And the behavior must depend on server policy. Session state for non-authenticated user must have new entropy every time it is being requested.
- logout response might also include session state for new unauthenticated state.
In my case, where is the clients are always trusted, they get consented automatically and issue session state for non-authenticate states too.

In my implementation, the session state consist of:
- entropy
- hash of:
  - entropy (same)
  - hash of cookie authentication (any cookie or their set that represents authentication state on the server) -- or empty for non-authenticated context
  - client_id
  - client's origin

> *Security Note*
> Since we have to be able to verify session state in browser context without unnecessary HTTP requests, the cookie for hashing must be accessible in the scripts, so not be HttpOnly. So, I, instead of auth cookie itself, exposing hash of that cookie as another cookie that kept in sync. It is handled by simple middle-ware that watches for request/response cookies and update if necessary.

One more important thing is that server must support non-interactive mode (`prompt=none`) which is not very well defined in the spec. This mode is being used intensively when client needs to silently renew session state without bothering user to go to server. That happens pretty often.
The server must not show any interaction required elements (even a button like 'go back to server'). This mode is used in a hidden iframe, so any interaction will block the flow. In my case, we just implicitly consent user to use current state, that ends with a redirect chain.

To implement all this, it was easy to override certain handlers in the provide to inject `session_state` to the response. The only authentication cookie hasher was implemented as a separate middleware.

#### Session Check iframe
This iframe is responsible to give an answer of the question:
> Is the session still valid for given `client_id` and `session_state`?

To answer, it must verify that
- client_id is valid
- the requester represents that client (by checking origin)
and give answer which is either "changed" or "unchanged" (or "error").

> *My implementation note*
> Client side script in the iframe gets hash of authentication cookie (which is a cookie itself), splits session_state into entropy and hash, then calculate expected hash from the known data to compare with. The script uses JavaScript implementation of cryptography hash calculation.

To implement, I used metadata endpoint and inject `session_check_iframe` endpoint with the iframe url.
I also introduced other middle-ware that handles that url. It simply uses the asset that is stored in a resource file.

To be continued...
