### ISSUE TITLE
'iat' claim in ID Token is not a JSON number as required in the spec.

### ISSUE THREAD

**Issue by mebehagen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#176]
The OpenID Connect Core 1.0 specification requires the ID Token claim "iat" to be a JSON number. Currently it is added as a string. Some clients (e.g. OpenAM) have trouble validating this token.

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug! :+1: 

FYI, this bug was only impacting the OWIN/Katana version and was just fixed as part of this commit: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/c713e70e5146e15455942ea932f2c6aa66afca90

It will be included in the next beta4 version, that should be released soon :clap:
