### ISSUE TITLE
Remove automatic resource/scope handling

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#186]
In the current bits, if you don't call `ticket.SetScopes(...)` or `ticket.SetResources(...)`, ASOS automagically uses the `scope` and `resource` parameters to set the scopes and the audiences of the access tokens it issues.

It's a really convenient feature, but I realized that people rarely implemented custom code to validate these parameters (e.g to ensure they correspond to real and accepted values). Though ASOS automatically ensures that a client application doesn't ask for more scopes/resources than the user initially granted during the authorization request (for the code flow) or the token request (for code and refresh token grants), it's still up to the developer to validate the initial scopes/resources values.

Question: should we remove this feature?

**Comment by damccull** [comment]
Perhaps instead of removing it from EVERYTHING, just move this into OpenIddict. That's your plug and play solution these days anyways, right? This would prevent the lack-of-validation behavior you're seeing by forcing developers using ASOS to do that, but would also allow those who want it to "just work easy" to avoid worrying about it. ASOS if you want power, OpenIddict for easy.

**Comment by PinpointTownes** [comment]
@damccull for OpenIddict, the ultimate plan is to add a new `Scope` entity and force the developers to establish a pre-defined list of accepted scopes. You can see the progress here: https://github.com/openiddict/core/pull/20 (/cc @ilmax).

For the audiences/resources, we'll probably suggest creating a client registration for each resource server (since in the introspection spec, a resource server is considered as an OAuth2 client).

**Comment by sunsided** [comment]
Would removing that ("really convenient") feature have any effects on existing code? If so, does that force developers to explicitly state their intentions using these methods? For me, OpenIddict (much like IdentityServer) is no option, but I'm guilty as well in not calling `SetScopes()` and `SetResources()`, mostly because I didn't even know about them until know. :worried:

**Comment by PinpointTownes** [comment]
> Would removing that ("really convenient") feature have any effects on existing code?

Yes, it will impact every existing app that doesn't explicitly call `SetScopes` and `SetResources`:

  - If you don't call `SetScopes`, ASOS won't issue an identity token nor a refresh token (since the `scope` parameter is ignored, `openid` and `offline_access` are not automatically added to the final scopes list).

  - If you don't call `SetResources`, ASOS won't set the `aud` claim in the JWT access token and since the JWT bearer middleware rejects tokens that don't mention an explicit `aud`, all the tokens issued by ASOS will be rejected. This is clearly a huge breaking change.

> If so, does that force developers to explicitly state their intentions using these methods?

Yep, that's the idea behind this change.

(FWIW and TBH, I'm not a huge fan of removing the automatic `resource`/`scope` support, but it seems a safer default behavior)

**Comment by sunsided** [comment]
Hm, sounds a bit weird though to not issue the `openid` scope in an OpenID server, regardless of the options; this seems like a behavior that should be left in to me. 

As for `offline_access`, I'd assume that's safer to remove: I see my colleagues happily requesting refresh tokens from my server without me ever allowing that (I remember them being issued automatically back then) - they can't use them due to missing client credentials, but they shouldn't receive them in the first place without me explicitly allowing that. There's more to client validation there that needs to be done manually anyway.

As for the audience claim, I'd expect it to be sent with a default value configurable by option, i.e. `options.DefaultAudience = "something";`. If and only if that value is set, ASOS could add it automatically (unless the user explicitly `SetResources` it.)

**Comment by PinpointTownes** [comment]
> Hm, sounds a bit weird though to not issue the openid scope in an OpenID server, regardless of the options; this seems like a behavior that should be left in to me.

Actually, it's not that weird: ASOS supports pure OAuth2 requests and won't return an identity token for a non-OIDC request.

> As for the audience claim, I'd expect it to be sent with a default value configurable by option, i.e. options.DefaultAudience = "something";. If and only if that value is set, ASOS could add it automatically (unless the user explicitly SetResources it.)

Not sure how I feel about adding a default "audience" (specially since it's not really different from calling `SetResources()`).

Though the JWT middleware doesn't like that, having no explicit audience in a token (even in a JWT token) is a totally valid and standard scenario: it just means "hey, I'm not constrained to a particular endpoint, accept me everywhere" (like a banknote). The new validation middleware will make that much easier, since we won't require an explicit audience.

**Comment by sunsided** [comment]
Well, in that case I've got nothing to complain about. Being explicit in what one wants is seldom a bad thing to do.

Am 4. Dezember 2015 22:41:18 MEZ, schrieb "Kévin Chalet" <notifications@github.com>:
>> Hm, sounds a bit weird though to not issue the openid scope in an
>OpenID server, regardless of the options; this seems like a behavior
>that should be left in to me.
>
>Actually, it's not that weird: ASOS supports pure OAuth2 requests and
>won't return an identity token for a non-OIDC request.
>
>> As for the audience claim, I'd expect it to be sent with a default
>value configurable by option, i.e. options.DefaultAudience =
>"something";. If and only if that value is set, ASOS could add it
>automatically (unless the user explicitly SetResources it.)
>
>Not sure how I feel about adding a default "audience" (specially since
>it's not really different from calling `SetResources()`).
>
>Though the JWT middleware doesn't like that, having no explicit
>audience in a token (even in a JWT token) is a totally valid and
>standard scenario: it just means "hey, I'm not constrained to a
>particular endpoint, accept me everywhere" (like a banknote). The new
>validation middleware will make that much easier, since we won't
>require an explicit audience.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/186#issuecomment-162089795

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PinpointTownes** [comment]
FYI, I already included this change on a big PR I'm working on locally. But TBH, I'm not sure removing the automatic scope/resource handling is worth the effort and the pain will ask to the ASOS users, specially since the security gain is rather marginal (well, you just avoid having `youporn.com` audiences in your tokens if you validate them :smile:).

**Comment by damccull** [comment]
Why not an option to automatically do it, configurable in startup. Opt in. Then you can make it off by default while giving the option to allow devs to still use this automatic feature. Prevent completely breaking code but make it safer by default and recommend the explicit options.

**Comment by DovydasNavickas** [comment]
I think what @damccull says is really fair way to transition everyone to using `ticket.SetScopes(...)` and `ticket.SetResources(...)`.

For now, we could do it opt-in mechanism, but leave it *ON* by default, so that none of the existing apps break.

Then, (aaaaand... we're back) add some documentation.. :clap: And maybe a minimap roadmap, stating coming breaking changes.

And when we feel that there was enough time (and documentation) for ASOS users (devs) to transition to setting both scopes and resources explicitly, we release a major version with breaking changes:
**"AspNet.Security.OpenIdConnect.Server": "2.0.0"**

What do you think about this scenario?

**Comment by PinpointTownes** [comment]
Actually, I think this is the right moment to add such a breaking change as all the existing apps will be broken due to the token type change, which will force ASOS users to come here to know how they are supposed to fix it. Adding it in a future version would postpone it by at least 3 or 4 months.

> For now, we could do it opt-in mechanism, but leave it ON by default, so that none of the existing apps break.

Well, leaving it ON by default defeats the objective of this ticket: making scope/resource safer by default :smile: 

Actually, re-enabling automatic scope/resource handling is rather easy (and has a merit: it's EXPLICIT! :smile:):

```csharp
ticket.SetResources(request.GetResources());
ticket.SetScopes(request.GetScopes());
```

**Comment by PinpointTownes** [comment]
Done :sob: 

ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/af8b29ac118c534323bf70e177592d5ec387a018
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/495d2f75403ebf46bb8b3d7f0cfbe91feed02850
