### ISSUE TITLE
If a token expired, the AspNet.Security.OpenIdConnect.Server throw an 500 internal server error, can it just throw 401 Unauthorized error?

### ISSUE THREAD

**Issue by TonyWoo** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#191]
If a token expired, the AspNet.Security.OpenIdConnect.Server throw an 500 internal server error.
The client will not know what happened, is it possible just throw 401 Unauthorized error? Thanks.

**Comment by PinpointTownes** [comment]
The issue you're seeing is likely caused by the JWT bearer middleware (that protects your API and validates access tokens) and not by ASOS itself.

Sadly, it's a known bug - [that was not fixed for RC1] (https://github.com/aspnet/Security/issues/411) - and it's quite difficult to work around it, [due to another unfixed bug in the security stack] (https://github.com/aspnet/Security/issues/555).

AFAIK, your only option is to write a middleware that catches the security exceptions thrown by the JWT bearer middleware (well, rather by the underlying library it uses: IdentityModel) and returns an appropriate 401 response.

You can also switch to the latest RC2 nightly builds, since this bug was fixed by @Tratcher recently.
__________

Note that we'll stop using JWT tokens by default in the next beta, so the JWT bearer middleware will no longer be necessary. See https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/185 for more information.
