### ISSUE TITLE
AuthenticationTicket.SetAudiences vs SetResources can be confusing

### ISSUE THREAD

**Issue by Sally-Xu** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#195]
From the function name, anybody would guess to use ticket.SetAudiences to set the Audiences of the ticket.  It would be better to have the name of a function to match what it really does. If a function such as SetAudiences is only used by internal code, maybe it should not be exposed as a public function.

**Comment by PinpointTownes** [comment]
> From the function name, anybody would guess to use ticket.SetAudiences to set the Audiences of the ticket.

There are actually multiple tickets, corresponding to the different types of tokens issued by ASOS: an access token ticket, an identity token ticket, an authorization code ticket and a refresh token ticket. 

When you call `SignInAsync()` or `Validate()`, your ticket is cloned and the resulting tickets are internally altered to include the appropriate audiences (for an access token: the resource server ; for an identity token: the client) so a global "audiences" list doesn't make much sense and that's why we use a "resources" property instead, that you can set via `SetResources`. Making `SetAudiences` is not an option as it can be used by advanced users from the `Serialize*Token` notifications to replace the default audiences.

That said, I agree it might be confusing. To mitigate that, we have basically 2 options:
* Determining whether `SetAudiences` has been called instead of `SetResources` and throwing an exception indicating how to use `SetResources`.
* Copying the "resources" from the "audiences" property.

**Comment by PinpointTownes** [comment]
I've finally opted for the second approach.

ASP.NET Core: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/9953bef82ec4cf9deeb13dbfebd70717fbc5dfd3
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/771ead694443ee0ebc2595802918910106893edf
