### ISSUE TITLE
Use the samples with refresh_tokens and local accounts

### ISSUE THREAD

**Issue by pierre-weceipt** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#204]
Hi, I've got a new question today :) 
I would like to update the sample server used in my app to use refresh_tokens and local accounts. I'm not really sure about the flows and different endpoints I need to call to implement these.
I'm not sure that refresh_tokens make sense for a mobile app as the client_id is saved in the code other than to allow revoking access.
Can you give me a quick hint on where I should look?

Thanks

**Comment by PinpointTownes** [comment]
Salut :smile: 

To use the `refresh_token` grant, you'll need to retrieve a `refresh_token` from the token endpoint using the authorization code flow: you **can't** retrieve a refresh token with the implicit flow (i.e `response_type=token` or `response_type=id_token token`). In ASOS, you don't have to implement anything server-side, as refresh tokens are automatically supported (just make sure to request the `offline_access` scope and to grant it: `ticket.SetScopes(new[] { "offline_access" })`).

OpenID Connect offers an alternative to the refresh token grant: [`prompt=none` authorization requests](http://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint). IMHO, this approach is less flexible, as the user must be connected (using cookies authentication) for the request to be accepted, which might be tricky with native apps using web views (cookies are often wiped when the web view is disposed). Since you're responsible of creating your own authorization endpoint, it's not implemented in ASOS, but OpenIddict offers native support for `prompt=none`.

**Comment by pierre-weceipt** [comment]
Bonjour,

I switched from implicit to authorization code flow, I added the `offline_access` scope in the request and the `AuthorizationController.cs` `Accept` enpoint (not really sure if It is really here that the ticket is set though) but I end up with the following error : `{"error":"invalid_grant","error_description":"Invalid ticket"}`.

**Comment by PinpointTownes** [comment]
This error indicates an invalid authorization code/refresh token (malformed or altered). Any chance you could verify everything is correctly flowed using Fiddler?

**Comment by pierre-weceipt** [comment]
OK, I was doing something stupid : I generated the `authorization_code` with the app and then for testing purpose used the code in fiddler to get the tokens... After doing it from the app I no longer have the error but I don't receive the `refresh_token`.

**Comment by pierre-weceipt** [comment]
I got it working, a misstype in `offline_access` was the last bug. Thanks again for your great help/guidance :)
