### ISSUE TITLE
[Question] - simple sample (implicit)

### ISSUE THREAD

**Issue by dazinator** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#241]
Hello,

Looking for some guidance :)
I have an ASP.NET 5 MVC application, that also hosts its own WEB API. It currently uses cookie authentication middleware, with a custom ticket data format so that it can read a custom auth cookie that was issued by another (older) application, and construct the Claims Identity.

This works, and as long as this cookie is sent in a request, then the Principal is established for the request. I am not using the ASP.NET Identity / User model at all. 

I am now looking to add some javascript to one of the MVC views inside the application, and I'd like to allow this JS to call the WEB API, and use token based "bearer" authentication, rather than sending the cookie each time. The way i'd like to do that is that Javascript app will essentially swap the cookie for a token by calling an /api/token endpoint sending the cookie. The token controller should then deal with the authenticated incoming request, grab the principal, and issue a token for the authenticated identity, which is returned to the JS client.

My first question is, where does the "client secret" fit in for this scenario? My current understanding is that for this type of application - the client secret makes no sense as it isn't really a secret anymore if it's served up in a browser. My second question - Is there any sample that shows OpenIdConnect being used to provide a token endpoint within an application, which is later consumed by some JS within the same application? - I believe this is called the "implicit" flow? I did glance within the samples directory but perhaps I missed it?

Many Thanks

**Comment by PinpointTownes** [comment]
Hey,

> The way i'd like to do that is that Javascript app will essentially swap the cookie for a token by calling an /api/token endpoint sending the cookie.

Though technically possible, this flow would be non-standard, as client apps are not supposed to send cookies to the token endpoint, which is a purely REST endpoint.

I'd recommend using an interactive flow like the authorization code or implicit flows instead, but if you really want to implement that flow, consider creating a custom grant (using the `GrantCustomExtension` event).

> My first question is, where does the "client secret" fit in for this scenario? My current understanding is that for this type of application - the client secret makes no sense as it isn't really a secret anymore if it's served up in a browser.

As you figured it out: nowhere, since JS apps are not able to keep their credentials secret. The implicit flow doesn't use client authentication at all, and you're responsible of rolling your own client authentication policy when using the authorization code flow or your own grant (in ASOS beta5, you need to override the `ValidateTokenRequest` event for that)

> My second question - Is there any sample that shows OpenIdConnect being used to provide a token endpoint within an application, which is later consumed by some JS within the same application? - I believe this is called the "implicit" flow? I did glance within the samples directory but perhaps I missed it?

The implicit flow doesn't use the token endpoint: the tokens are directly returned from the authorization endpoint.

We don't have a JS/implicit flow sample ATM, mainly because the authorization server part would be exactly the same as the existing MVC server sample ; only the client side would change.

We'll definitely provide a JS sample, but time is a terrible limiting factor, so it will have to wait a bit.

**Comment by dazinator** [comment]
Thank you for this. That's everything I needed to know :)
