### ISSUE TITLE
End points are not available for ApiExplorer

### ISSUE THREAD

**Issue by Ciantic** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#260]
I would like to have all my API end points, including OpenId ones, documented so they need to be available for [ApiExplorer](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.ApiExplorer).

Currently e.g. connect/token is not available to ApiExplorer, and thus SwaggerGen can't document it and I don't get the nice test client Swagger provides either.

I tried to wrap end-points using my own controller, but couldn't do that either because the relevant calls are private (and in internal classes) e.g.

[InvokeTokenEndpointAsync](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/82fbd5e34bc075dac6781307ca9d8f8f14a9466b/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Exchange.cs#L23) which handles the default `connect/token` end point.

For me it would be ideal if I the end-points were available as actions, so I could compose them in own Controller thus they could be documented normally.

**Comment by PinpointTownes** [comment]
> Currently e.g. connect/token is not available to ApiExplorer, and thus SwaggerGen can't document it and I don't get the nice test client Swagger provides either.

These endpoints are directly managed at the middleware level and don't rely on ASP.NET Core MVC, which is needed by SwaggerGen to generate the documentation you're looking for.

TBH, we have no plans to replace all these endpoints by MVC actions because ASOS has been designed as a low-level authentication middleware and is similar to the other security middleware in the ASP.NET Core stack (e.g https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs).

IMHO, I'm not sure to understand why you'd want to generate Swagger documentation for all these endpoints, since they are based on OAuth2/OpenID Connect standards.
