### ISSUE TITLE
Bare X.509 key values in JSON Web Key Set document

### ISSUE THREAD

**Issue by mebehagen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#267]
We use a X.509 certificate for signing. The generated jwks document lists the signing key with the certificate in the x5c parameter. But the specification [http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata] states in section3: "The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. **When used, the bare key values MUST still be present and MUST match those in the certificate.**"

The last sentence indicates that (for RSA keys) also the 'N' and 'E' parameters need to be presented.

I assume this could easily be fixed. As we have a client that uses the Nimbus Java library, which can only handle the bare keys (no certificates) this would help a lot.

**Comment by PinpointTownes** [comment]
ASOS supports raw RSA keys for a while now (I even wonder if the very first beta didn't support it): https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Discovery.cs#L291-L292

You can easily register a RSA signing key using the `AddKey` extension:

```cs
app.UseOpenIdConnectServer(options => {
    options.SigningCredentials.AddKey(new RsaSecurityKey(...));
});
```

That said, if you're using the ASOS beta5 pre-prerelease bits (for the upcoming ASP.NET Core RC2 packages), you might be hitting a bug caused by a recent change in IdentityModel. I'll fix that soon.

**Comment by mebehagen** [comment]
Yes, I was aware that you are supporting raw RSA keys. But for some reason we are using a certificate right from the start, and I think, I can remember that you also wrote somewhere that you would recommend using certificates instead of raw keys. Anyway, as the spec says that the jwks must use the N and E parameters additionally to the x5c parameter, I thought, it would be easy to add the two mentioned lines of code (or similar ones) to the code-block a few lines above.

**Comment by PinpointTownes** [comment]
> I can remember that you also wrote somewhere that you would recommend using certificates instead of raw keys.

I recommend using X509 certificates on production because they are easier to store than RSA keys, but of course, you're free to use raw RSA keys as signing keys.

> Anyway, as the spec says that the jwks must use the N and E parameters additionally to the x5c parameter

So you'd just like us to include `e` and `n` when returning a JWK key corresponding to a certificate? 

I'm not opposed to that (specially if it's a spec requirement), but I'd like to make sure it's something most libraries can handle correctly... I wouldn't be surprised if IdentityModel was not able to deal with that.

**Comment by mebehagen** [comment]
Yep, it is much easier to deal with certificates than with keys in production environment.
And yes, would be great, although I am of course not sure, whether all client libraries can handle that. Microsoft clients should support it if you for example look at [https://login.windows.net/common/discovery/keys](url).

**Comment by PinpointTownes** [comment]
Alright, let's try to include that in ASOS beta5 then :smile:

**Comment by PinpointTownes** [comment]
PR ready: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/270.

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/7d41a1da42ffc3f64c4bd9b2ef9939a9e348cfe2.
