### ISSUE TITLE
Investigation - be more DI friendly

### ISSUE THREAD

**Issue by ilmax** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#275]
This issue came out of a discussion with @PinpointTownes, essentially it would be (IMO) much more user friendly to allow `OpenIdConnectServerProvider` to be a simple service and move away from the service locator.

To make this possible we should change `OpenIdConnectServerOptions` to remove the property

``` cs
public IOpenIdConnectServerProvider Provider { get; set; } = new OpenIdConnectServerProvider();
```

this should be substituted by something else (e.g. the IOpenIdConnectServerProvider Type that the consumer would use.
Instead of: `options.Provider = new MyProvider();` there could be something that `options.ProviderType = typeof(MyProvider)`;

This change allows ASOS to use the `IOpenIdConnectServerProvider` as a service thus making everyone's life much better :)

Note from @PinpointTownes 

> One thing to remember is that we need to be able to have 2 ASOS instances in the same pipeline with a different provider for each instance.
> 
> It would be inconsistent with the other security middleware in ASP.NET Core. Not a trivial change.

**Comment by PinpointTownes** [comment]
> Instead of: options.Provider = new MyProvider(); there could be something that options.ProviderType = typeof(MyProvider);

Actually, I guess we should have both, since one must be able to use the delegate approach for simple scenarios:

```csharp

app.UseOpenIdConnectServer(options => {
    options.Provider = new OpenIdConnectServerProvider {
        // Implement OnValidateAuthorizationRequest to
        // support interactive flows (code/implicit/hybrid).
        OnValidateAuthorizationRequest = async context => { ... },

        // Implement OnValidateTokenRequest to support flows using the token endpoint
        // (code/refresh token/password/client credentials/custom grant).
        OnValidateTokenRequest = async context => { ... }
    };
});
```

**Comment by olivier-spinelli** [comment]
Avoiding the locator is important for me too. What about supporting both with an explicit naming like this **UseInlineImplementation** xor **UseProvider**:
```
app.UseOpenIdConnectServer(options => {
    options.UseInlineImplementation( p => {
        // Implement OnValidateAuthorizationRequest to
        // support interactive flows (code/implicit/hybrid).
        p.OnValidateAuthorizationRequest = async context => { ... },

        // Implement OnValidateTokenRequest to support flows using the token endpoint
        // (code/refresh token/password/client credentials/custom grant).
        p.OnValidateTokenRequest = async context => { ... }
     })
});
```
And:
```
app.UseOpenIdConnectServer( options => options.UseProvider( typeof(MyProvider) ) );
```
Of course, an `InvalidOperationException` should be raised when both are set.
Another option would be to publish 2 different "Use" on the app (app.UseOpenIdConnectServerInline end app.UseOpenIdConnectServerType).

My 2 cents and Thank SO MUCH for this, this is more than great!

**Comment by PinpointTownes** [comment]
Salut :smile: 

Alright, I'll ping the ASP.NET guys and see if/how/when we could adopt a common pattern (since the entire ASP.NET Core security stack is impacted by this design decision). If we can't, we'll likely end up having something specific to ASOS.

@Eilon hey! Any idea on who's the right person to ping for that? :smile: 

Related tickets: https://github.com/aspnet/Options/issues/11, https://github.com/aspnet/Security/issues/863

**Comment by olivier-spinelli** [comment]
That would be great! 
(And, please, forgive me for my second crappy proposal: "to publish 2 different "Use" on the app", this is a terrible idea :).)

**Comment by PinpointTownes** [comment]
@HaoK looks like you're in charge of https://github.com/aspnet/Security/issues/863. Please ping me when you start working on it, I'd like to coordinate our efforts :smile:

**Comment by HaoK** [comment]
Sure what are you thinking?  For 1.1 we have to be fairly careful to avoid breaking changes, so it will likely be limited to the scope of something like getting the IClaimsTransformer as a service from DI instead of pulling it always from Options.  But we can certainly try to do something more elegant...

**Comment by PinpointTownes** [comment]
@HaoK whoooooops, looks like I missed your reply, sorry :fearful: 

My two cents: I believe the entire aspnet/Security stack needs more DI love, not just the claims transformation stack (e.g all the events classes).

@ilmax's approach looks like a good compromise: introduce a new `EventsType` property that allows one to set the component type that will be resolved from the DI container and fallback to the existing `Events` property when `EventsType` is not set.

**Comment by PinpointTownes** [comment]
Postponed to 1.0.0-rc1 as the DI story for events in ASP.NET Core is still being discussed.

**Comment by PinpointTownes** [comment]
Note: you can follow the progress here: https://github.com/aspnet/Security/pull/1014.

**Comment by PinpointTownes** [comment]
Such support has been added to the ASP.NET Core 2.0 version of ASOS as part of https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/4a6224177d1a3d33a2f3e523805b3e8cf0e11c98 (it won't be implemented in the OWIN/Katana version due to the lack of generic DI support).

The MVC server sample has been updated to demonstrate how to use the new `ProviderType` property:
  - https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs#L52
  - https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs#L96
