### ISSUE TITLE
refresh_token can be used multiple times

### ISSUE THREAD

**Issue by smbecker** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#279]
In practice, a refresh_token should only be allowed to be used once. After that, any subsequent attempts to use the same refresh_token should be rejected even if in a valid lifetime window. Currently, I can use a refresh_token as many times as I want as long as I am within the window. Is it possible to reject tokens after they have been used already?

**Comment by smbecker** [comment]
In the same vein, an old access_token should be rejected once the refresh_token is used regardless of whether or not the access_token has expired.

**Comment by PinpointTownes** [comment]
> In practice, a refresh_token should only be allowed to be used once. After that, any subsequent attempts to use the same refresh_token should be rejected even if in a valid lifetime window. Currently, I can use a refresh_token as many times as I want as long as I am within the window. Is it possible to reject tokens after they have been used already?

Yes, but that's something you need to implement yourself since it requires a backing store.

FWIW, I just implemented "single use" of refresh tokens in OpenIddict using the `SerializeRefreshToken` and `GrantRefreshToken` events (it will be released in the next few weeks).

> In the same vein, an old access_token should be rejected once the refresh_token is used regardless of whether or not the access_token has expired.

If you want to support access token revocation, you'll have to implement that check at the resource server level, in the JWT bearer/validation middleware. You can use the [`ValidateToken`](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/blob/dev/src/AspNet.Security.OAuth.Validation/IOAuthValidationEvents.cs#L27) event for that.

**Comment by smbecker** [comment]
Ok, that's fine. I'll have to wait and see how you did it for OpenIddict. Is there anything pushed anywhere that I could reference?

**Comment by PinpointTownes** [comment]
No need to wait for the OpenIddict commit, it's really trivial to implement yourself:

  - Create a DB entry in `SerializeRefreshToken` using the unique identifier associated with the token (`context.Ticket.GetTicketId()`).
  - In `GrantRefreshToken`, check whether the entry still exists and reject the request if the token was revoked. Remove the entry to prevent future reuses.

**Comment by smbecker** [comment]
Are the tokens signed with the user security stamp so that changing the security stamp revokes the tokens? Sorry, I know this has probably gone beyond the scope of this issue (and perhaps this particular repo/project).

**Comment by PinpointTownes** [comment]
> Are the tokens signed with the user security stamp so that changing the security stamp revokes the tokens?

Currently, yes; updating the security stamp invalidates all the refresh tokens previously issued.
With the built-in revocation feature, I'm considering removing it (one could still list the refresh tokens associated with a user and revoke them manually).

That's a point we'll have to discuss with @ilmax.

**Comment by PinpointTownes** [comment]
Of course, my previous question applies to OpenIddict, not ASOS itself.

**Comment by smbecker** [comment]
Does that apply access_tokens as well?

**Comment by ilmax** [comment]
>Does that apply access_tokens as well?

Do you mean token signing with user security stamp?

**Comment by smbecker** [comment]
Yes, do any active access tokens get revoked as well once a security stamp changes? Or is that something that I would also have to implement myself in [`ValidateToken`](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/blob/dev/src/AspNet.Security.OAuth.Validation/IOAuthValidationEvents.cs#L27) as mentioned above?

**Comment by ilmax** [comment]
AFAIK active access token are not stored, so from an ASOS perspective there is nothing to revoke. But we should really ask to @PinpointTownes

**Comment by PinpointTownes** [comment]
> Yes, do any active access tokens get revoked as well once a security stamp changes? Or is that something that I would also have to implement myself in ValidateToken as mentioned above?

In ASOS, you're free to implement that using the new revocation endpoint (that accepts access tokens) and the `ValidateTicket` event of the validation middleware.

OpenIddict will likely never implement access token revocation, because we'd have to store them in a database and make a DB call for each API request received by the resource server, which would have serious performance implications. We'll only support refresh token revocation and suggest people to use a short access token lifetime.

**Comment by PinpointTownes** [comment]
> AFAIK access token are not stored, so from an ASOS perspective there is nothing to revoke. But we should really ask to @PinpointTownes

True, the access tokens issued by ASOS are always self-contained (the same rule applies to both JWT and opaque tokens). That said, nothing prevents you from implementing access tokens revocation in ASOS if you want to.
