### ISSUE TITLE
RC1 to RC2 migration

### ISSUE THREAD

**Issue by tim-cools** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#284]
Hi,

I'm migrating my React SPA example from RC1 to RC2. Most changes were easy to track, but I have following questions:

- *ValidateClientAuthentication* and *ValidateClientRedirectUri* are not on *OpenIdConnectServerProvider* any more. What is the recommended place to do the checks?

- I used to use the *SetScopes* and *SetResources* method on *AuthenticationProperties*. These does not exist anymore. What is the best way to set them?

	```
var properties = new AuthenticationProperties();
	properties.SetScopes(new[]
	{
		OpenIdConnectConstants.Scopes.OpenId,
		OpenIdConnectConstants.Scopes.Email,
		OpenIdConnectConstants.Scopes.Profile,
		OpenIdConnectConstants.Scopes.OfflineAccess
	});
	properties.SetResources(new[] { "http://localhost:3000/" });
```
			
- This is not from this library, but you might know the answer. I used to get a unique id from the OpenIdConnectRequest

            var request = HttpContext.GetOpenIdConnectRequest();
            var redirectUri = "/account/authorize/complete?unique_id=" + request.GetUniqueIdentifier();

But this method does not exist anymore. Do you know what the recommended way is to get a unique id.

- I had following code to serialize the refresh token

```
public override async Task SerializeRefreshToken(SerializeRefreshTokenContext context)
        {
            context.RefreshToken = await context.SerializeTicketAsync();

            await StoreRefreshToken(context);
        }
```

But the *SerializeTicketAsync* method is gone now. How can I Serialize the ticket now?

Many thanks for your time!

**Comment by PinpointTownes** [comment]
Hey,

> ValidateClientAuthentication and ValidateClientRedirectUri are not on OpenIdConnectServerProvider any more. What is the recommended place to do the checks?

These methods have been merged with the more general `ValidateXYZRequest` events to help reduce the potential DB roundtrips (since you had to retrieve the client application details from both methods).

  - `ValidateClientAuthentication` -> `ValidateTokenRequest`/`ValidateIntrospectionRequest`/`ValidateRevocationRequest`. in most apps, you'll only need to implement `ValidateTokenRequest`.

  - `ValidateClientRedirectUri` -> `ValidateAuthorizationRequest`.

> I used to use the SetScopes and SetResources method on AuthenticationProperties. These does not exist anymore. What is the best way to set them?

You can directly create a ticket:

```csharp
var ticket = new AuthenticationTicket(principal, null, context.Options.AuthenticationScheme);
ticket.SetScopes("x", "y", "z");
```

> This is not from this library, but you might know the answer. I used to get a unique id from the OpenIdConnectRequest

It is, actually. It was renamed to `GetRequestId()` and the parameter is now named `request_id` instead of `unique_id`.

> But the SerializeTicketAsync method is gone now. How can I Serialize the ticket now?

It was removed for this exact reason, actually: encouraging people not to store the refresh token as-is. Instead, you should only store the unique identifier associated with the refresh token. You can retrieve it using `context.Ticket.GetTicketId()`: 

https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/Infrastructure/OpenIddictProvider.Serialization.cs#L27

https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/Infrastructure/OpenIddictProvider.Revocation.cs#L98

> Many thanks for your time!

:clap: :clap:

**Comment by tim-cools** [comment]
Thanks a lot for the support, I got everything working!

The only part that was not working as described is the rename of the parameter *request_id* to *unique_id*. If I do this it is not working anymore. Is this documented somewhere?

**Comment by PinpointTownes** [comment]
> request_id to unique_id

Maybe I wasn't clear: it was previously named `unique_id` but it's `request_id` now :smile:

**Comment by tim-cools** [comment]
Makes sense :-D
