### ISSUE TITLE
Question: what are differences between ASOS and IdentityServer4 project

### ISSUE THREAD

**Issue by tedvanderveen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#350]
Looks like there is another quite similar open source framework for OpenID Connect and OAuth 2.0, also aiming at ASP.NET Core: https://github.com/IdentityServer/IdentityServer4
What are the main differences between ASOS and IdentityServer4 from your perspective?
(PS: we use your OpenIddict library currently and are a big fan! 👍)

**Comment by PinpointTownes** [comment]
> (PS: we use your OpenIddict library currently and are a big fan! :+1:)

Thanks for the kind word :smile: 

> What are the main differences between ASOS and IdentityServer4 from your perspective?

  - ASOS was forked from Katana's `OAuthAuthorizationServerMiddleware` and uses the same events model as the OIDC client middleware developed by MSFT: unlike IdSrv, it fully integrates with ASP.NET Core's authentication middleware pipeline, which allows doing advanced stuff like handling authorization/token requests in your own controllers instead of at the middleware level. This is what allows you to do [things like this in OpenIddict](https://github.com/openiddict/openiddict-samples/blob/master/samples/CodeFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L82). For more information about the events model, you can read [this blog post](http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-creating-your-own-authorization-provider/).

  - ASOS' only mission is to help you deal with the OAuth2/OIDC protocol details: everything else is totally out of scope. This means that concepts like users, applications or stores are completely inexistant in ASOS (e.g unlike IdSrv, ASOS doesn't have any user store contract: you're free to bring your own implementation... and your own abstraction).

  - ASOS is entirely based on a low-level approach that uses the events class (aka `OpenIdConnectServerProvider`) as the main source of extensibility, exactly like the other security middleware in ASP.NET Core. This allows implementing advanced routines that are invoked at each stage of the request processing. IdSrv has a much more classical approach and exposes higher level APIs (read tons of specialized interfaces and implementations that you have replace if you want to customize how requests are handled).

  - Developers using ASOS are responsible of implementing things like client authentication or consent pages. Of course, this prevents ASOS from being used as a turnkey solution you can use without writing any code, but it offers full flexibility to decide exactly how client authentication should be implemented. IdSrv on the other hand handles most of these things for you.

It's interesting to note that IdSrv4 is radically different from IdSrv3 (whose flexibility was absolutely horrible... its hard dependency on ASP.NET Web API was my main motivation to start working on ASOS) and now uses the same approach as ASOS for things like user authentication or UI pages (that are no longer built-in and must be added by the dev).

Hope it'll help.

**Comment by tedvanderveen** [comment]
@PinpointTownes many thanks for your response and please keep up the great work!
