### ISSUE TITLE
Grating offline_access to public apps

### ISSUE THREAD

**Issue by georgeonofrei** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#378]
Hello,

What's your opinion regarding grating offline_access to public applications?
I've looked through the standard and have not found an explicit indication that grating public apps the offline_access is a big security issue.

I think it is as a public app are not capable of securely keeping their password, let alone a refresh token, but
I need some second opinion on this.

Thanks,
George

**Comment by PinpointTownes** [comment]
Hey,

> I think it is as a public app are not capable of securely keeping their password, let alone a refresh token, but I need some second opinion on this.

The fact a client application can be considered as confidential or public is actually completely orthogonal to the fact refresh tokens can be (safely) used or not, which is why this scenario is definitely supported and allowed (for mobile apps, it's even necessary in practice).

It's worth noting that unlike client credentials, refresh tokens represent the resource owner, not the client application itself, so there's no real point preventing the resource owner from accessing his own refresh tokens (i.e that are bound to his own account/resources).

What's important in this case is to protect them against other users. For that, you should consider using the secure credentials stores offered by the platforms you target (e.g Keychain on iOS, Keystore on Android or PasswordVault on Windows).

Hope it'll help.
