### ISSUE TITLE
Implicit flow with offline_access 

### ISSUE THREAD

**Issue by georgeonofrei** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#386]
Hello,

Is there any way to enable offline_access for implicit flow?
Or is this specified precisely in the standard as not being advised?

Thanks,
George

**Comment by PinpointTownes** [comment]
Hey,

> Is there any way to enable offline_access for implicit flow?

As recommended by the OIDC spec, ASOS won't reject your request if you ask for the `offline_access` scope and will simply ignore it:

> Upon receipt of a scope parameter containing the offline_access value, the Authorization Server MUST ignore the offline_access request unless the Client is using a response_type value that would result in an Authorization Code being returned.

Generally speaking, **no refresh token can be returned from the authorization endpoint**, even if you grant the `offline_access` scope via `ticket.SetScopes(...)`. Otherwise, [it would violate the OAuth2 spec](https://tools.ietf.org/html/rfc6749#section-4.2.2):

> The authorization server MUST NOT issue a refresh token.

![image](https://cloud.githubusercontent.com/assets/6998306/22852083/0bada6ba-f035-11e6-89e0-c2f444375067.png)
