### ISSUE TITLE
No error when adding AuthorizeAttribute to a controller

### ISSUE THREAD

**Issue by zagros** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#390]
Hi

I'm not sure if this is an issue with my code or the framework.

I've used your Sample code you have in the repo to add OAuth to a brand new Web API project (using Aspnet Core and VS 2017).

I get the token returned when I create a new token (i.e OnHandleTokenRequest() is called properly and I can get a valid token using your example).

Here's where things fall apart. I use this token now in Postman to POST to a FooController (the URL being `/api/foo/test`) which literally has an `[Authorize, HttpPost, Route("/api/foo/post")]` attribute and returns a string "success" ... without the authorize, I tested using post man and I see the results btw.

That's it, that's my entire project so far .... so ...

The problem is this. Although using your starter code I get the token without a problem, when I use this "bearer blahblahblah" to post to the above `/api/foo/test`, the request fails with a 401 status and zero content body length.  No errors or anything to help to see where I went wrong

I don't have EntityFramework, not is this an MVC app (it's Web Api) for me to have authorization endpoints or cookie based authentication

**Comment by PinpointTownes** [comment]
Hi,

> the request fails with a 401 status and zero content body length

That's actually the expected behavior, as defined by the OAuth2 bearer specification.

It's worth noting that the latest validation/introspection middleware packages now return the errors detail as part of the `WWW-Authenticate` response header, like the JWT middleware: https://tools.ietf.org/html/rfc6750#section-3

Did you have something else in mind? (e.g a JSON error response?)
