### ISSUE TITLE
Loosing data protection keys while publishing to docker. The identity token handler refused to read the token

### ISSUE THREAD

**Issue by horse315** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#430]
Hello!
I am publishing my server to docker and each time i start a new version of container all the tokens issued previously become invalid:
_The identity token handler refused to read the token_
I have a simple configuration with signing credentials with certificate, but data protection keys are regenerated every time I start a new container. So I'd like to know what else should I do to save user sessions valid between deployments?

**Comment by PinpointTownes** [comment]
Hey. 

FYI: the debug message you're seeing is expected: when the introspection endpoint receives a token, it has to determine whether it's an access token, an identity token, an authorization code or a refresh token by trying to deserialize it. In this case, the OIDC server middleware tried to read the token as an identity token and failed to do so (which is expected, since the token is likely an access token). 

To configure Data Protection and ensure the key ring is shared between your instances, read https://docs.microsoft.com/fr-fr/aspnet/core/security/data-protection/configuration/overview

**Comment by horse315** [comment]
Thanks for the link!
I decided to add generated key file to container, now it works!
