### ISSUE TITLE
DeserializeIdentityToken is not called by logout flow

### ISSUE THREAD

**Issue by thuannguy** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#467]
Hi,
I'm using ASOS to implement an OIDC server. Great library! Now that I need to implement logout flow and found out that when handling a logout request, DeserializeIdentityToken is not called. I tried the AspNet.Security.OpenIdConnect.Samples and got the same issue:

![image](https://user-images.githubusercontent.com/395484/29301061-c48cdcaa-81a3-11e7-83d8-0273b392567c.png)

In the screenshot above, the DeserializeIdentityToken event isn't called at all. Is this a known issue? Or do I need to handle that myself?

Thank you in advance :)

**Comment by kevinchalet** [comment]
> Hi,
I'm using ASOS to implement an OIDC server. Great library!

Hey, glad you like it :smile: 

> Now that I need to implement logout flow and found out that when handling a logout request, DeserializeIdentityToken is not called.

When a logout request (aka end session request) is received, the `id_token_hint` parameter is not automatically "decoded".

If you need to resolve the identity corresponding to this identity token (e.g because you want to use it for UI-less logouts), you must call `var principal = HttpContext.Authentication.AuthenticateAsync(OpenIdConnectServerDefaults.AuthenticationScheme)` to retrieve the `ClaimsPrincipal` containing all the identity token claims.

If you do that, the `DeserializeIdentityToken` event should be called.

**Comment by kevinchalet** [comment]
On an unrelated note, you don't need to use `context.HttpContext.GetOpenIdConnectRequest()` in the ASOS events. Simply use `context.Request`.

**Comment by thuannguy** [comment]
Thank you very much. While I can copy code from that method to my own code, knowing how to do it the right way is always better :)
