### ISSUE TITLE
Validation for public clients (mobile app in particular)

### ISSUE THREAD

**Issue by CameronWills** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#472]
Hi,

I'm just a little confused about what logic is needed when using the 'Authorization Code' flow in a public mobile app. My id server will have several public facing mobile apps consuming it without explicit consent forms.

Your [blog post](http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-implementing-the-authorization-code-and-implicit-flows/#Implementing-ValidateTokenRequest-to-validate-the-grant-type-and-the-client-application-credentials) mentions:

> For instance, here's what you'll typically do for a mobile application, for which client authentication cannot be enforced:
```
public override Task ValidateTokenRequest(ValidateTokenRequestContext context)
{
    // Reject the token requests that don't use
    // grant_type=authorization_code or grant_type=refresh_token.
    if (!context.Request.IsAuthorizationCodeGrantType() &&
        !context.Request.IsRefreshTokenGrantType())
    {
        context.Reject(
            error: OpenIdConnectConstants.Errors.UnsupportedGrantType,
            description: "Only the authorization code and refresh token " +
                         "grants are accepted by this authorization server");
        return Task.FromResult(0);
    }
    // Since there's only one application and since it's a public client
    // (i.e a client that cannot keep its credentials private), call Skip()
    // to inform the server the request should be accepted without 
    // enforcing client authentication.
    context.Skip();
    return Task.FromResult(0);
}
```

A few questions:
1. Would it be bad to add a check for a client_id and client_secret here? Or does the server logic treat token requests without a client_id/client_secret differently following `context.Skip()`? Dubious or untrusted in some way..

2. Or is there just little point in checking the client_id/client_secret in the `Authorization Code` flow because the security really comes from checking the response_type + client_id + redirect_uri during `ValidateAuthorizationRequest`?

3. Should I explicitly check for `context.Request.CodeChallenge` in to enforce PKCE for public client applications? And if so does this belong in `ValidateAuthorizationRequest` ?

Thanks and great work by the way.

**Comment by kevinchalet** [comment]
>  Or does the server logic treat token requests without a client_id/client_secret differently following context.Skip()? Dubious or untrusted in some way..

When you call `context.Skip()` instead of `context.Validate()`, the request is indeed considered as "not confidential" and all the tokens issued as part of this request are also marked as "not confidential", which has a few implications when it comes to introspect or validate them (e.g when a refresh token is confidential, client authentication is required when making a `grant_type=refresh_token` request and the caller must be one of the listed presenters).

> Would it be bad to add a check for a client_id and client_secret here?

Nothing fundamentally bad, but it would be better to avoid that: only tokens that were really issued using a private channel (typically, as part of a backchannel token request when using the code flow) should be marked as confidential. Otherwise, ASOS will run useless security checks that would be easily bypassed if I could extract the client secret from your mobile app.

> Or is there just little point in checking the client_id/client_secret in the Authorization Code flow because the security really comes from checking the response_type + client_id + redirect_uri during ValidateAuthorizationRequest?

There's absolutely no point in using a client secret for an app that can't keep it secret. The security indeed comes from the callback dance.

> Should I explicitly check for context.Request.CodeChallenge in to enforce PKCE for public client applications? And if so does this belong in ValidateAuthorizationRequest ?

You can. I know other servers like IdentityServer offer an option to make it mandatory but IMHO, it's totally useless and doesn't offer any security improvement whatsoever.

PKCE is only useful to harden the callback part (i.e the moment the authorization server redirects the user agent back to the mobile app): if an evil app installed on the user's device triggers an authorization request on behalf of the legitimate app, nothing prevents if from also sending the "mandatory" PKCE parameters (since it initiates the authentication dance with all the parameters it wants).
