### ISSUE TITLE
Should UserInfo use Json or Jwt token format by default?

### ISSUE THREAD

**Issue by thuannguy** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#476]
Hi,
According to http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse, UserInfo response can be Json or a JWT token.

> If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be application/jwt. The response MAY be encrypted without also being signed. If both signing and encryption are requested, the response MUST be signed then encrypted, with the result being a Nested JWT, as defined in [JWT]. 

As-is, if I check code correctly, ASOS returns UserInfo in a Json response and the [serialization class](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Serialization.cs) doesn't have a method to serialize user info.

In my opinion, because using JWT token is more secure, is there any reason that ASOS chose to use Json over JWT for UserInfo token? And if I am to support JWT token for UserInfo, is the correct way to add the same methods and properties to relevant classes as those for the IdToken?

Thank you for reading :)

**Comment by kevinchalet** [comment]
Hey,

> In my opinion, because using JWT token is more secure, is there any reason that ASOS chose to use Json over JWT for UserInfo token?

A very simple one: JSON userinfo responses are universally supported, unlike signed/encrypted JWT responses :sweat_smile: 

JWT userinfo response is not a first-class citizen in ASOS because it doesn't offer a much stronger security level as signing and encryption are already supposed to be enforced at the transport level (using TLS).

To implement such support in your app, you can use the `HandleUserinfoRequest` even to take control of the response: write the JWT to the response stream (`context.HttpContext.Response.Body`) and call `context.HandleResponse()`.

**Comment by thuannguy** [comment]
Yeah, thinking about it, using an access token to request for userinfo is not different from using it to request a typical RESTful service which usually returns pure json anyway.

Thank you very much :)
