### ISSUE TITLE
IdentityToken Serializer should allow empty or null subject

### ISSUE THREAD

**Issue by kinosang** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#495]
These codes below reject the null or empty subject claim, but in client credentials flow the subject should (can) be null.

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/1f46760a7a3995471aa5919a48ac3aee4e9120d7/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Serialization.cs#L317-L321

**Comment by kevinchalet** [comment]
While we could theoretically avoid having a `sub` in the identity tokens returned for non-OIDC flows (since they are custom parameters after all), it's not really something I'm a huge fan of, to be honest.

When using the client credentials flow, the identity represents the client application itself so the `sub` claim is usually the client identifier or a unique DB identifier that corresponds to this app.

Do you have a scenario in mind where this approach wouldn't be suitable?

**Comment by kinosang** [comment]
@PinpointTownes I figured out that the `sub` claim represents a human, but there's no interactive human presented for client credentials grant type.

And when client call APIs with `access_token` from client credentials flow, it may conflict with subject of an user.

**Comment by kevinchalet** [comment]
Where did you see the `sub` represented a person? The definition is deliberately generic enough not to limit it to this scenario:

> The "sub" (subject) claim identifies the principal that is the subject of the JWT.

To solve your concern, consider adding a second claim indicating whether the subject/principal is a user or a machine (e.g `sub_tp`).

**Comment by kinosang** [comment]
@PinpointTownes thanks for your reply and the solution.

**Comment by kevinchalet** [comment]
My pleasure :+1:
