### ISSUE TITLE
Add claims_supported by default to configuration output

### ISSUE THREAD

**Issue by NinoFloris** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#522]
https://openid.net/specs/openid-connect-discovery-1_0.html
recommends adding claims_supported by default.

>claims_supported
RECOMMENDED. JSON array containing a list of the Claim Names of the Claims that the OpenID Provider MAY be able to supply values for. Note that for privacy or other reasons, this might not be an exhaustive list.

**Comment by kevinchalet** [comment]
ASOS being a framework, it's hard to return a precise list since we have no control over the claims used/added by the developer. That said, we could only list the basic protocol claims, just like what we do in OpenIddict: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerOptions.cs#L53-L60

**Comment by NinoFloris** [comment]
Sure however that argument would go for grant types and scopes as well yet those are included by default ;)

**Comment by NinoFloris** [comment]
@PinpointTownes Thanks for the super quick response!
