### ISSUE TITLE
Using the antiforgery middleware

### ISSUE THREAD

**Issue by jpmnteiro** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#533]
(apologies in advance if the topic is covered in the documentation or past issues (search didn't return any meaningful results).

I have a website running with the OpenIdConnectServer middleware handling the authentication. I've also added the AntiForgery service as I expose some POST endpoints for various operations.

My question is, given that I configure the server's auth endpoint like this:

    options.TokenEndpoint = new PathString("/api/auth/token")

Do I have to/how can I enable the anti-forgery verification on the token's endpoint, given that the token request is a POST and, as far I understand it, should also be subject to anti-forgery checks?

Many thanks in advance!

**Comment by kevinchalet** [comment]
> Do I have to/how can I enable the anti-forgery verification on the token's endpoint, given that the token request is a POST and, as far I understand it, should also be subject to anti-forgery checks?

Definitely not: the token endpoint is basically an API endpoint for which you'll never want to use things like cookie or Windows authentication (that make endpoints vulnerable to XSRF due to the fact authentication details are automatically sent by a browser).

As such, there's no reason to use antiforgery to protect it. Using that would also make your endpoint completely non-standard and would hurt interoperability with most/all OAuth 2.0 clients.

**Comment by jpmnteiro** [comment]
Makes sense, thank you for the clarification!

**Comment by kevinchalet** [comment]
You're welcome!
