### ISSUE TITLE
Problems with MVC 6

### ISSUE THREAD

**Issue by manfredsteyer** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#81]
Hi,

I've just played around with the current ASP.NET-5-Implementation and found out, that the current VS 2015 CTP presents the following error after downloading AspNet.Security.OpenIdConnect.Server via NuGet:

Dependency System.Collections.Specialized >= 4.0.0-beta-22606 could not be resolved	SecureWebAPIDemo	c:\users\manfred\documents\visual studio 2015\Projects\SecureWebAPIDemo\src\SecureWebAPIDemo\project.json	1

Wishes,
Manfred

**Comment by PinpointTownes** [comment]
Hey @manfredsteyer! :smile:

Unlike the OWIN/Katana 3 version, the ASP.NET 5 version uploaded on MyGet is really old and probably references outdated/unpublished packages. Sadly, this is due to AppVeyor using an incompatible version of NuGet, that doesn't support the new format and prevents nightly builds from being uploaded to MyGet (see https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openidconnect-server/build/1.0.0-beta2-120 for an example).

I'll build it locally and manually upload the latest binaries on MyGet. In the meantime, you can try cloning the repository or downloading the zip solution.

**Comment by PinpointTownes** [comment]
Additionally, it looks like MyGet is having a hard time trying to handle the load since the BUILD event :smile:

**Comment by manfredsteyer** [comment]
Great. Thx.

**Comment by PinpointTownes** [comment]
I just uploaded the new packages (using my local cache to build them) on MyGet, but their service is currently unable to serve the massive load they receive since VS 2015 RC is out.

Even AppVeyor and Travis-CI haven't been able to download the necessary packages:
https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openidconnect-server/build/1.0.0-beta2-125
https://travis-ci.org/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/builds/60858294

Don't hesitate to run `dnu restore` multiple times if you have "task canceled" exceptions when restoring packages.

**Comment by PinpointTownes** [comment]
@manfredsteyer did the new package solve your issue? :cold_sweat:

**Comment by PinpointTownes** [comment]
FYI, the AppVeyor/NuGet bug was fixed recently, which unlocked our vNext nightly builds.

Make sure to update your NuGet settings to use the new MyGet repository: __https://www.myget.org/F/aspnet-contrib/__
